import { VideoProject } from './types';

export const VIDEO_PROJECTS: VideoProject[] = [
  {
    id: '1',
    youtubeId: 'Ia4i2oQJPek',
    title: 'Obsession Edit: Marty supreme X Whiplash',
    description: 'A high-energy edit blending Marty Supreme and Whiplash visuals.',
    thumbnail: 'https://img.youtube.com/vi/Ia4i2oQJPek/maxresdefault.jpg',
    category: 'After Effects',
    featured: true,
  },
  {
    id: '2',
    youtubeId: '0mcFWvLMqSk',
    title: 'anime x racing',
    description: 'Fast-paced anime edit synced with high-speed racing footage.',
    thumbnail: 'https://img.youtube.com/vi/0mcFWvLMqSk/maxresdefault.jpg',
    category: 'Anime Edit',
    featured: true,
  },
  {
    id: '3',
    youtubeId: '55rPI3ymBEc',
    title: '2026 new year edit',
    description: 'Celebrating the start of 2026 with a dynamic visual journey.',
    thumbnail: 'https://img.youtube.com/vi/55rPI3ymBEc/maxresdefault.jpg',
    category: 'Special',
    featured: true,
  },
  {
    id: '4',
    youtubeId: 'ZsVBw312PmQ',
    title: 'your name edit',
    description: 'Emotional storytelling edit featuring scenes from Your Name.',
    thumbnail: 'https://img.youtube.com/vi/ZsVBw312PmQ/maxresdefault.jpg',
    category: 'Anime Edit',
  },
  {
    id: '5',
    youtubeId: 'yw4V8gk8MTg',
    title: 'gojo edit',
    description: 'Showcasing the power and style of Satoru Gojo.',
    thumbnail: 'https://img.youtube.com/vi/yw4V8gk8MTg/maxresdefault.jpg',
    category: 'Jujutsu Kaisen',
  },
  {
    id: '6',
    youtubeId: 'nPVQ2zW3E5U',
    title: 'sukuna edit: "id let the world burn"',
    description: 'Dark and intense Sukuna edit with a focus on atmosphere.',
    thumbnail: 'https://img.youtube.com/vi/nPVQ2zW3E5U/maxresdefault.jpg',
    category: 'Jujutsu Kaisen',
  },
  {
    id: '7',
    youtubeId: 'wDDHQcWEe3U',
    title: 'a gojo edit',
    description: 'Another perspective on the strongest sorcerer.',
    thumbnail: 'https://img.youtube.com/vi/wDDHQcWEe3U/maxresdefault.jpg',
    category: 'Jujutsu Kaisen',
  },
  {
    id: '8',
    youtubeId: '1usR331IKfk',
    title: 'A Silent Voice Edit',
    description: 'A touching tribute to the beautiful animation of A Silent Voice.',
    thumbnail: 'https://img.youtube.com/vi/1usR331IKfk/maxresdefault.jpg',
    category: 'Anime Edit',
  },
  {
    id: '9',
    youtubeId: 'V4AVDIjWvKU',
    title: 'my first time using after effects',
    description: 'My very first project exploring the power of After Effects.',
    thumbnail: 'https://img.youtube.com/vi/V4AVDIjWvKU/maxresdefault.jpg',
    category: 'Milestone',
  },
  {
    id: '10',
    youtubeId: 'fitF6SJ-95E',
    title: '300 sub special',
    description: 'Celebrating 300 subscribers on my YouTube channel!',
    thumbnail: 'https://img.youtube.com/vi/fitF6SJ-95E/maxresdefault.jpg',
    category: 'Milestone',
  },
  {
    id: '11',
    youtubeId: 'hGfrUIWTl8g',
    title: "itadori's breakdown",
    description: 'Capturing the raw emotion of Itadori Yuji.',
    thumbnail: 'https://img.youtube.com/vi/hGfrUIWTl8g/maxresdefault.jpg',
    category: 'Jujutsu Kaisen',
  },
  {
    id: '12',
    youtubeId: 'zz3NUv4qFjQ',
    title: "itadori's dominance",
    description: 'Showcasing the growth and strength of Itadori.',
    thumbnail: 'https://img.youtube.com/vi/zz3NUv4qFjQ/maxresdefault.jpg',
    category: 'Jujutsu Kaisen',
  },
];
